spring:
  datasource:
    url: jdbc:mysql://localhost:3308/supermarket
    username: supermarket
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 300000
      pool-name: MyDataSource
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 100ms
    password:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: templates/**

  thymeleaf:
    cache: false


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dkm.supermarket.bean
